version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "http"
      - "--domain"
      - "ibex-glorious-muskrat.ngrok-free.app"
      - "frontend:80"
      - "--log=stdout"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: 2tj7We9zM6ET9BOOawECurNJbYy_7dYvWb81mgFCdkuNkk7U
    ports:
      - "4040:4040"
    networks:
      brickseekr_network:
        ipv4_address: 172.18.0.11

  backend:
    image: brickseekr_backend:latest
    container_name: brickseekr_backend
    build:
      context: ./brickseekr-back
    working_dir: /src
    env_file:
      - brickseekr-back/.env
    environment:
      MODE: DEVELOPMENT
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
    ports:
      - "8080:8080"
    networks:
      brickseekr_network:
        ipv4_address: 172.18.0.2

  frontend:
    image: brickseekr_frontend:latest
    container_name: brickseekr_frontend
    build:
      context: ./brickseekr-web
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - ngrok
    networks:
      brickseekr_network:
        ipv4_address: 172.18.0.3

networks:
  brickseekr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16


